name: nobsheads
version: "0.1.0"
author: TxT
main: com.txt.nobsheadsplugin.NoBsHeadsPlugin
api-version: "1.17"
commands:
  heads:
    description: Command to buy heads and to configure the plugin
    usage: /<command> buy [name]